llm:
  models:
    summarization:
      api_type: "openai"
      model_name: "gpt-3.5-turbo"
      base_url: "https://api.openai.com/v1"
      api_key: "YOUR_SUMMARIZATION_API_KEY"

    advanced_reasoning:
      api_type: "openai"
      model_name: "gpt-4"
      base_url: "https://api.openai.com/v1"
      api_key: "YOUR_ADV_REASONING_API_KEY"

vector_store:
  db_path: "./vector_db"

search_config:
  api_type: "google"
  api_key: "YOUR_SEARCH_API_KEY"
  cse_id: "YOUR_CSE_ID_IF_GOOGLE"
